{
    "codecov": {
        "notify": {
            "wait_for_ci": true
        }
    },
    "coverage": {
        "status": {
            "project": {
                "default": {
                    "threshold": 0.70
                }
            }
        }
    }
}