{
    "codecov": {
        "notify": {
            "wait_for_ci": true
        }
    },
    "coverage": {
        "range": 60..85,
        "status": {
            "project": {
                "default": {
                    "threshold": 25%
                }
            },
            "patch": {
                "default": {
                    "threshold": 25%,
                }
            }
        }
    }
}