sudo: false

language: node_js

node_js:
  - 11

cache: npm

install:
  - "npm install"
  - "npm install codecov -g"

script:
  - "npm run test && npm run test:webpack"
  - "codecov"

matrix:
  fast_finish: true
  include:
    - env: TEST_TYPE=lint
    - env: TEST_TYPE=test:dist
    - env: TEST_TYPE=test:lib
    - env: TEST_TYPE=test:es
    - env: TEST_TYPE=test:dom
    - env: TEST_TYPE=test:node

script:
  - scripts/travis-script.sh
