# travis用来对 包大小变化 + 代码质量 + 测试覆盖率 进行提报。
# npm一套的构建流水在github actions上进行。
sudo: false

language: node_js

node_js:
  - 11

cache: npm

install:
  - "npm install"
  - "npm install codecov -g"

script:
  - "npm run test"
  - "codecov"

matrix:
  fast_finish: true
  include:
    - env: TEST_TYPE=lint
    - env: TEST_TYPE=test:dist
    - env: TEST_TYPE=test:lib
    - env: TEST_TYPE=test:es
    - env: TEST_TYPE=test:dom
    - env: TEST_TYPE=test:node

script:
  - bin/travis.sh
