name: checker

on: 
  push:
    branches:
      - master
      - staging
      - feature
      - 'sprint@*'
  pull_request:
    types: [opened,reopened]

jobs:
  # 创建node_modules缓存
  install: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.20.x] 
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm install

      - name: cache node_modules
        uses: actions/cache@v1
        env:
          cache-name: cached-node-modules
        with:
          path: ~/.npm
          key: build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

  bundleSize: 
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      # 转移缓存
      - name: restore cached node_modules
        uses: actions/cache@v1
        env:
          cache-name: cached-node-modules
        with:
          path: ~/.npm
          key: build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: run bundleSize checker
        uses: sarthak-saxena/JSBundleSize@master
        with:
          build_command: npm run dist
          dist_path: 'dist'
          token: ${{ secrets.GITHUB_TOKEN }}

  codecov: 
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      # 转移缓存
      - name: restore cached node_modules
        uses: actions/cache@v1
        env:
          cache-name: cached-node-modules
        with:
          path: ~/.npm
          key: build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: unit(component) test
        run: npm run test:coverage

      - name: run codecov reporter
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: mlz-admin
          fail_ci_if_error: true