name: publish

on:
  push:
    branches:
      - 'feat/*'
  pull_request:
    types: [closed]
    branches:
      - release

jobs:
  publish: 
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup zh-cn timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
          
      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm install

      - name: execute test
        run: npm run test:coverage

      - name: lint code
        run: npm run lint

      - name: build dist
        run: npm run dist
      
      - name: tag a tag
        run: npm run version
        env:
          CI: true