name: PR checker

on: [pull_request,push]

jobs:
  install: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.20.x] 
    steps:
      - uses: actions/checkout@master

      - name: cache node_modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: setup dependencies
        run: npm install

  bundleSize: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.20.x] 
    needs: install
    steps:
      - uses: actions/checkout@master
        
      - name: restore cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: run bundleSize checker
      - uses: sarthak-saxena/JSBundleSize@master
        with:
          build_command: npm run dist
          dist_path: 'dist'
          token: ${{ secrets.GITHUB_TOKEN }}

  codecov: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.20.x] 
    needs: install
    steps:
      - uses: actions/checkout@master
        
      - name: restore cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: run codecov reporter
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./clover.xml
          flags: uitests,unittest
          name: mlz-admin
          fail_ci_if_error: true